package neuralnet

import "sort"

// TextData represents a single data instance containing a document and its associated label.
// The document is stored as a slice of words, and the label is represented as an integer.
type TextData struct {
	Document []string // The document represented as a slice of words.
	Label    int      // The label associated with the document.
}

// GenerateWordToRank computes a ranking for the most frequently occurring words in the provided dataset.
// It processes the input text data, counts word frequencies, excludes specified stop words, and then
// selects the top `vocabSize` words based on frequency. The ranking starts at 1 for the most frequent word.
//
// Parameters:
//   - textData: A slice of TextData, where each element contains a document represented as a slice of words.
//   - vocabSize: The maximum number of words to include in the ranking. Only the top `vocabSize` words are returned.
//   - stopWords: A slice of strings representing the stop words that should be excluded from the ranking.
//
// Returns:
//   - A map[string]int where each key is a word and its corresponding value is an integer rank (starting at 1)
//     indicating its frequency order (with 1 being the most frequent).
func GenerateWordToRank(textData []TextData, vocabSize int, stopWords []string) map[string]int {
	wordFreq := make(map[string]int)

	// -------------------------------
	// 1. Count frequencies with NEGATION handling
	// -------------------------------
	for _, data := range textData {
		doc := data.Document
		limit := len(doc)

		for i := 0; i < limit; i++ {
			word := doc[i]

			// NEGATION pattern detection
			if i+1 < limit {
				next := doc[i+1]

				if word == "not" || word == "didnt" || word == "wasnt" ||
					word == "isnt" || word == "werent" || word == "never" {

					combined := "NOT_" + next
					wordFreq[combined]++
					i++ // skip next word
					continue
				}
			}

			wordFreq[word]++
		}
	}

	// -------------------------------
	// 2. Convert freq map → sorted list (DETERMINISTIC)
	// -------------------------------
	stopMap := make(map[string]bool)
	for _, sw := range stopWords {
		stopMap[sw] = true
	}

	// Build a stable word list
	type wc struct {
		word  string
		count int
	}

	words := make([]string, 0, len(wordFreq))
	for w := range wordFreq {
		if !stopMap[w] {
			words = append(words, w)
		}
	}

	// Sort lexical first (secondary key)
	sort.Strings(words)

	// Convert to word-count list
	wcList := make([]wc, 0, len(words))
	for _, w := range words {
		wcList = append(wcList, wc{w, wordFreq[w]})
	}

	// Stable sort by:
	// 1. freq DESC
	// 2. word ASC (tie-breaker)
	sort.SliceStable(wcList, func(i, j int) bool {
		if wcList[i].count == wcList[j].count {
			return wcList[i].word < wcList[j].word
		}
		return wcList[i].count > wcList[j].count
	})

	// -------------------------------
	// 3. Assign deterministic ranks
	// -------------------------------
	wordToRank := make(map[string]int)

	rank := 1
	for _, entry := range wcList {
		if rank > vocabSize {
			break
		}
		wordToRank[entry.word] = rank
		rank++
	}

	return wordToRank
}

// OneHotBag converts a document into a one-hot encoded bag-of-words vector based on the provided word-to-rank mapping.
// It processes the document up to a maximum of `maxWords` and marks the presence of words that are within the top `vocabSize` ranks.
//
// Parameters:
//   - doc: A slice of strings representing the words in a document.
//   - wordToRank: A map generated by GenerateWordToRank, where each word is assigned a rank (starting at 1 for the most frequent).
//   - maxWords: The maximum number of words from the document to consider for encoding.
//   - vocabSize: The size of the vocabulary (i.e., the length of the resulting one-hot vector).
//
// Returns:
//   - A slice of float64 with length equal to `vocabSize`, where each position corresponds to a word rank.
//     A value of 1.0 indicates that the word with the corresponding rank is present in the document.
func OneHotBag(doc []string, wordToRank map[string]int, maxWords, vocabSize int) []float64 {
	vec := make([]float64, vocabSize)

	// --- 1. Limit the number of words ---
	limit := len(doc)
	if limit > maxWords {
		limit = maxWords
	}

	// --- 2. Build normalized Bag-of-Words with NEGATION handling ---
	for i := 0; i < limit; i++ {
		word := doc[i]

		// Detect negation patterns: not X, didnt X, wasn't X, never X
		if i+1 < limit {
			next := doc[i+1]

			if word == "not" || word == "didnt" || word == "wasnt" || word == "isnt" || word == "werent" || word == "never" {
				combined := "NOT_" + next
				if r, ok := wordToRank[combined]; ok && r > 0 && r <= vocabSize {
					// vec[r-1]++
					vec[r-1] = 1
				}
				i++ // skip next word
				continue
			}
		}

		// Standard single word
		if r, ok := wordToRank[word]; ok && r > 0 && r <= vocabSize {
			// vec[r-1]++
			vec[r-1] = 1
		}
	}

	// // --- 3. Normalize (TF) ---
	// denom := float64(limit)
	// if denom < 1 {
	// 	denom = 1
	// }
	// for i := 0; i < vocabSize; i++ {
	// 	vec[i] /= denom
	// }

	return vec
}

func buildWordToRank(freq map[string]int, stopWords []string) map[string]int {
	stopWordsMap := make(map[string]bool)
	for _, word := range stopWords {
		stopWordsMap[word] = true
	}
	// Sort by freq descending
	type wordCount struct {
		word  string
		count int
	}
	var wcList []wordCount
	for w, c := range freq {
		if stopWordsMap[w] {
			continue
		}
		wcList = append(wcList, wordCount{w, c})
	}
	sort.Slice(wcList, func(i, j int) bool {
		return wcList[i].count > wcList[j].count
	})

	wordToRank := make(map[string]int)
	for i, wc := range wcList {
		wordToRank[wc.word] = i + 1 // rank starts at 1
	}
	return wordToRank
}

func keepTopKWords(wordToRank map[string]int, K int) map[string]int {
	newMap := make(map[string]int)
	for w, r := range wordToRank {
		if r <= K {
			newMap[w] = r
		}
	}
	return newMap
}
